version: 2
jobs:
  macosbuild:
    macos:
      xcode: "10.0.0"
    steps:
      - run: brew install go berkeley-db leveldb libsodium maven haskell-stack && stack setup
      - checkout
      - run: cat config.mk | sed 's/BUILDS = linux-64 darwin-64/BUILDS = darwin-64/' > config.mk2 && mv config.mk2 config.mk && mkdir -p build
      - run: make BUILDS=darwin-64 circleci-macos 
  linuxbuild:
    machine: true
    steps:
      - checkout
      - run: cat config.mk | sed 's/BUILDS = linux-64 darwin-64/BUILDS = linux-64/' > config.mk2 && mv config.mk2 config.mk
      - run: make BUILDS=linux-64 qbc && make test
workflows:
  version: 2
  test:
    jobs:
      - macosbuild
      - linuxbuild
